plugins:
  - package: robotx_behavior_tree
    name:
      - move_goal_action
      - configure_controller_action
behavior:
  description:
    package: robotx_bt_planner
    path : behavior_trees/go.xml