plugins:
  - package: robotx_behavior_tree
    name:
      - move_to_front_pose_of_object
      - move_goal_action
behavior:
  description:
    package: robotx_bt_planner
    path : behavior_trees/go_around_object.xml