plugins:
  - package: robotx_behavior_tree
    name:
      - move_to_gate_action
      - move_goal_action
behavior:
  description:
    package: robotx_bt_planner
    path : behavior_trees/move_to_gate2.xml